### ISSUE TITLE
Would you like to work together?

### ISSUE THREAD

**Issue by trey-wallis** [Stardusten/ob-table-enhancer#8]
Hi Stardusten.

I'm Trey. I am the maker of the plugin `Obsidian Notion-Like Tables`. I am very impressed with your plugin. You seem to have a lot of Obsidian.md plugin experience. I have been looking for someone to collaborate with me on my Obsidian plugin. Would you be interested in working together?

**Comment by Stardusten** [comment]
Thank you very much for your offer, but I'm afraid I don't have much time, because I'm still a college student and need to cope with my busy school work, and this plugin is also something I took time to write during my vacation.

However, there are still many imperfections in this plugin. The index part of my plugin is also inspired from your `Obsidian Notion-Like Tables`. I think there will be many more opportunities for us to be able to communicate with each other in the future and make our plugins even better.
